
CREATE TABLE Product
(
  productID BIGINT NOT NULL,
  bleachingCode INT NOT NULL,
  defaultLanguage varchar(300) NOT NULL,
  dryCleaningCode INT NOT NULL,
  dryingCode INT NOT NULL,
  fasteningTypeCode INT NOT NULL,
  ironingCode INT NOT NULL,
  pulloutTypeCode INT NOT NULL,
  sapPacket INT NOT NULL,
  updateImages BOOLEAN NOT NULL,
  waistLineCode INT NOT NULL,
  washabilityCode INT NOT NULL,
  PRIMARY KEY (productID)
);

CREATE TABLE Product_Detail
(
  cedi varchar(300) NOT NULL,
  childWeightFrom DECIMAL(10,1) NOT NULL,
  childWeightTo DECIMAL(10,1) NOT NULL,
  color_code INT NOT NULL,
  color_description varchar(300) NOT NULL,
  countryImages BOOLEAN NOT NULL,
  defaultSku BOOLEAN NOT NULL,
  preferredEan varchar(300) NOT NULL,
  sapAssortmentLevel varchar(10) NOT NULL,
  sapPrice DECIMAL(11,2) NOT NULL,
  season varchar(10) NOT NULL,
  showOnLineSku BOOLEAN NOT NULL,
  size_code varchar(10) NOT NULL,
  size_description varchar(300) NOT NULL,
  skuID INT NOT NULL,
  skuName varchar(300) NOT NULL,
  stateOfArticle BOOLEAN NOT NULL,
  umSAPPrice varchar(5) NOT NULL,
  volume DECIMAL(11,2) NOT NULL,
  weight DECIMAL(10,1) NOT NULL,
  productID BIGINT NOT NULL,
  PRIMARY KEY (skuID),
  FOREIGN KEY (productID) REFERENCES Product(productID)
);

CREATE TABLE Product_Header
(
  productID BIGINT NOT NULL,
  bag BOOLEAN NOT NULL,
  bleachingDescription varchar(300) NOT NULL,
  brand varchar(30) NOT NULL,
  brandCode INT NOT NULL,
  catalog varchar(30) NOT NULL,
  composition varchar(30) NOT NULL,
  creationDateInDatabase DATE NOT NULL,
  drinkHolder BOOLEAN NOT NULL,
  dryCleaningDescription varchar(300) NOT NULL,
  dryingDescription varchar(300) NOT NULL,
  EShopDisplayName varchar(300) NOT NULL,
  EShopLongDescription varchar(300) NOT NULL,
  ergonomicSeat BOOLEAN NOT NULL,
  fasteningTypeDescription varchar(300) NOT NULL,
  fasteningTypeTextile varchar(300) NOT NULL,
  flat BOOLEAN NOT NULL,
  freeDelivery BOOLEAN NOT NULL,
  gender varchar(10) NOT NULL,
  indicatorOfItHasToBeAssembled BOOLEAN NOT NULL,
  ironingDescription varchar(300) NOT NULL,
  lastDateChanged DATE NOT NULL,
  lastUserChanged varchar(30) NOT NULL,
  productFeatures varchar(300) NOT NULL,
  productMissingFeatures varchar(300) NOT NULL,
  pulloutType varchar(30) NOT NULL,
  pulloutTypeDescription varchar(300) NOT NULL,
  punnet BOOLEAN NOT NULL,
  sapCategoryID INT NOT NULL,
  sapCategoryName varchar(30) NOT NULL,
  sapDivisionID INT NOT NULL,
  sapDivisionName varchar(30) NOT NULL,
  sapFamilyDescription varchar(300) NOT NULL,
  sapFamilyID INT NOT NULL,
  sapFamilyName varchar(30) NOT NULL,
  sapMacroCategoryID varchar(30) NOT NULL,
  sapMacrocategoryName varchar(30) NOT NULL,
  sapName varchar(30) NOT NULL,
  sapUniverseID varchar(30) NOT NULL,
  sapUniverseName varchar(30) NOT NULL,
  showOnLine BOOLEAN NOT NULL,
  sizeGuide varchar(30) NOT NULL,
  userOfCreation varchar(30) NOT NULL,
  waistLineDescription varchar(300) NOT NULL,
  washability varchar(300) NOT NULL,
  washabilityDescriptionAttribute varchar(300) NOT NULL,
  zipStopper BOOLEAN NOT NULL,
  PRIMARY KEY (productID),
  FOREIGN KEY (productID) REFERENCES Product(productID)
);